import { StyleSheet } from 'react-native';
import variables from '../../css/VariablesBase.styles';

const styles = StyleSheet.create({
  container: {
    padding: variables.spacingMd,
    backgroundColor: variables.colorSurfacePrimary,
    borderRadius: variables.borderRadiusLg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
    width: '90%',
    alignSelf: 'center',
    marginBottom: variables.spacingMd,
  },
  title: {
    textAlign: 'center',
    color: variables.colorTextPrimary,
    marginBottom: variables.spacingMd,
    fontSize: 22,
    fontWeight: 'bold',
  },
  categoriasContainer: {
    marginBottom: 16,
  },
  categoriasTitle: {
    color: variables.colorTextTertiary,
    marginBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: variables.colorBorderSecondary,
    paddingBottom: 5,
    fontWeight: 'bold',
    fontSize: 16,
  },
  categoriasList: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
  },
  categoriaItem: {
    backgroundColor: variables.colorSurfacePrimary,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderRadius: variables.borderRadiusLg,
    fontSize: variables.fontSizeSm,
    fontWeight: '500',
    color: variables.colorTextPrimary,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  categoriaItemActive: {
    backgroundColor: variables.colorActive,
    color: variables.colorWhite,
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  categoriaItemText: {
    color: variables.colorTextPrimary,
    fontWeight: '500',
  },
  categoriaItemTextActive: {
    color: variables.colorWhite,
    fontWeight: 'bold',
  },
  listInner: {
    flexDirection: 'column',
    gap: 25,
  },
  noticiaItem: {
    backgroundColor: variables.colorSurfaceTertiary,
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    overflow: 'hidden',
    flexDirection: 'column',
    padding: variables.spacingMd,
    borderWidth: 1,
    borderColor: variables.colorBorderTertiary,
    marginBottom: 16,
  },
  noticiaItemHeader: {
    padding: 15,
  },
  noticiaItemTitle: {
    color: variables.colorTextTertiary,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  noticiaItemImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderRadius: variables.borderRadiusSm,
    marginBottom: 8,
  },
  noticiaItemDetails: {
    paddingHorizontal: 15,
    paddingBottom: 15,
    flexDirection: 'column',
    flexGrow: 1,
  },
  noticiaItemCategory: {
    backgroundColor: '#3498db',
    color: '#fff',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: variables.borderRadiusMd,
    fontSize: 13,
    alignSelf: 'center',
    margin: 10,
    overflow: 'hidden',
  },
  noticiaItemResumen: {
    fontSize: variables.fontSizeSm,
    color: variables.colorTextSecondary,
    marginVertical: variables.spacingSm,
  },
  noticiaItemDate: {
    fontSize: 15,
    fontWeight: '600',
    color: variables.colorTextPrimary,
    marginTop: 4,
  },
  noticiaItemAuthor: {
    fontSize: 15,
    fontWeight: '600',
    color: variables.colorTextPrimary,
    marginTop: 4,
  },
  noNoticiasContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
  },
  noNoticiasMessage: {
    color: '#888',
    fontSize: 18,
    textAlign: 'center',
  },
});

export default styles;
