import { StyleSheet } from 'react-native';
import { light } from '../../src/css/VariablesBase.styles';

export default StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: light.colorSurfaceOverlay,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    width: '90%',
    maxHeight: '95%',
    backgroundColor: light.colorSurfacePrimary,
    borderRadius: light.borderRadiusLg,
    borderWidth: 2,
    borderColor: light.colorBorderPrimary,
    padding: light.spacingLg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
    flexDirection: 'column',
    gap: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: light.colorBorderPrimary,
    paddingBottom: 16,
  },
  closeBtn: {
    fontSize: 24,
    paddingHorizontal: 8,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: light.colorBorderPrimary,
    borderRadius: light.borderRadiusFull,
    color: light.colorTextPrimary,
  },
  title: {
    textAlign: 'center',
    fontSize: 29,
    color: light.colorTextPrimary,
    fontWeight: 'bold',
    flex: 1,
  },
  list: {
    flexGrow: 1,
    marginVertical: 0,
    padding: 0,
  },
  item: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: light.spacingXs,
    borderRadius: light.borderRadiusMd,
    borderWidth: 1,
    borderColor: light.colorBorderPrimary,
    paddingVertical: light.spacingSm,
    paddingHorizontal: light.spacingMd,
    borderBottomWidth: 1,
    borderBottomColor: light.colorBorderPrimary,
    position: 'relative',
    marginBottom: 8,
    backgroundColor: light.colorWhite,
  },
  itemLast: {
    borderBottomWidth: 0,
  },
  itemNoDisponible: {
    borderColor: light.colorDanger,
  },
  imagen: {
    width: '80%',
    maxHeight: 150,
    borderRadius: light.borderRadiusMd,
    resizeMode: 'cover',
    marginBottom: 8,
  },
  itemText: {
    fontSize: 16,
    color: light.colorTextSecondary,
    fontWeight: '500',
  },
  comercio: {
    fontSize: light.fontSizeSm,
    fontWeight: '700',
    color: light.colorTextPrimary,
  },
  controlesCantidad: {
    backgroundColor: light.colorSurfaceTertiary,
    padding: light.spacingSm,
    borderWidth: 1,
    borderColor: light.colorBorderSecondary,
    borderRadius: light.borderRadiusPill,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    marginVertical: 8,
  },
  cantidadText: {
    fontSize: 16,
    minWidth: 90,
    textAlign: 'center',
    color: light.colorTextPrimary,
  },
  cantidadBtn: {
    backgroundColor: light.colorSurfaceSecondary,
    borderWidth: 1,
    borderColor: light.colorBorderSecondary,
    color: light.colorTextPrimary,
    borderRadius: light.borderRadiusFull,
    width: 40,
    height: 40,
    fontSize: light.fontSizeLg,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  cantidadBtnText: {
    color: light.colorTextPrimary,
    fontSize: light.fontSizeLg,
    fontWeight: 'bold',
  },
  eliminarBtn: {
    backgroundColor: light.colorSurfaceSecondary,
    borderWidth: 1,
    borderColor: light.colorBorderSecondary,
    borderRadius: light.borderRadiusFull,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  total: {
    textAlign: 'right',
    paddingTop: 24,
    borderTopWidth: 2,
    borderTopColor: light.colorBorderPrimary,
    fontWeight: 'bold',
    fontSize: 18,
    color: light.colorTextPrimary,
  },
  acciones: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  btnPagar: {
    backgroundColor: '#2980b9',
    color: light.colorWhite,
    borderRadius: light.borderRadiusMd,
    paddingVertical: 8,
    paddingHorizontal: 16,
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  btnLimpiar: {
    backgroundColor: '#f1f1f1',
    color: '#7f8c8d',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: light.borderRadiusMd,
    paddingVertical: 8,
    paddingHorizontal: 16,
    fontSize: 14,
    fontWeight: 'bold',
  },
  vacio: {
    textAlign: 'center',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mensaje: {
    fontSize: 18,
    color: '#7f8c8d',
    marginTop: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  nota: {
    width: '100%',
    padding: 12,
    backgroundColor: light.colorSurfaceTertiary,
    color: light.colorTextTertiary,
    borderWidth: 1,
    borderColor: light.colorBorderTertiary,
    borderRadius: light.borderRadiusSm,
    fontSize: 16,
    minHeight: 100,
    marginBottom: 8,
    textAlignVertical: 'top',
  },
  itemNoDisponibleOverlay: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.7)',
    zIndex: 2,
  },
  itemNoDisponibleText: {
    backgroundColor: light.colorSurfaceSecondary,
    color: light.colorTextSecondary,
    borderRadius: light.borderRadiusPill,
    fontSize: light.fontSizeSm,
    paddingVertical: light.spacingSm,
    paddingHorizontal: light.spacingMd,
    borderWidth: 1,
    borderColor: light.colorBorderSecondary,
    fontWeight: '700',
    textAlign: 'center',
    marginRight: 8,
  },
});
