import { StyleSheet } from 'react-native';
import variables from '../../css/VariablesBase.styles';

const BeneficiariosListaStyles = StyleSheet.create({
  container: {
    padding: 20,
    minHeight: '100%',
    flex: 1,
    alignItems: 'center',
    backgroundColor: variables.colorSurfacePrimary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 500,
    marginBottom: 20,
    position: 'relative',
    justifyContent: 'center',
  },
  headerTitle: {
    flexGrow: 1,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    margin: 0,
  },
  addMemberButtonContainer: {
    width: '100%',
    maxWidth: 500,
    alignItems: 'flex-end',
    marginTop: 20,
  },
  addMemberButton: {
    backgroundColor: '#28a745',
    color: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: variables.borderRadiusLg,
    fontSize: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  membersGrid: {
    flexDirection: 'column',
    gap: 15,
    width: '100%',
    maxWidth: 500,
  },
  memberCard: {
    flexDirection: 'row',
    backgroundColor: variables.colorSurfacePrimary,
    borderRadius: variables.borderRadiusLg,
    paddingVertical: 12,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    alignItems: 'center',
    gap: 5,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  memberPhoto: {
    width: 80,
    height: 80,
    borderRadius: 9999,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: variables.colorBorderSpan,
    backgroundColor: variables.colorWhite,
    flexShrink: 0,
  },
  memberDetails: {
    flexGrow: 1,
    minWidth: 150,
  },
  memberDetailsH3: {
    fontSize: 16,
    color: variables.colorTextPrimary,
    margin: 0,
    fontWeight: 'bold',
  },
  memberDetailsP: {
    fontSize: 14,
    color: variables.colorTextSecondary,
    margin: 0,
  },
  qrCodeContainer: {
    padding: 5,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: variables.borderRadiusSm,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 0,
    flexShrink: 0,
  },
  memberActions: {
    flexDirection: 'column',
    gap: 20,
    color: variables.colorTextSecondary,
    alignItems: 'center',
    marginLeft: 8,
  },
  noMembersMessage: {
    textAlign: 'center',
    color: '#777',
    fontSize: 16,
    marginTop: 50,
  },
  formLabel: {
    fontSize: 14,
    color: '#333',
    textAlign: 'left',
    paddingHorizontal: 8,
    fontWeight: '600',
    marginBottom: 4,
  },
  formInput: {
    width: '100%',
    padding: 8,
    borderWidth: 1,
    borderColor: variables.colorBorderSecondary,
    borderRadius: variables.borderRadiusSm,
    fontSize: 14,
    backgroundColor: variables.colorSurfaceSecondary,
    color: variables.colorTextPrimary,
    marginBottom: 8,
  },
});

export default BeneficiariosListaStyles;
