import { StyleSheet } from 'react-native';
import {light} from '../../src/css/VariablesBase.styles';

const variables = light;

const EditarPerfilStyles = StyleSheet.create({
  container: {
    width: '90%',
    alignSelf: 'center',
    padding: variables.spacingMd,
    borderRadius: variables.borderRadiusLg,
    backgroundColor: variables.colorSurfacePrimary,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'column',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 500,
    marginBottom: 20,
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 24,
    flexGrow: 1,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  photoSection: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 30,
  },
  currentPhoto: {
    width: 150,
    height: 150,
    borderRadius: 9999,
    resizeMode: 'cover',
    backgroundColor: variables.colorSurfacePrimary,
    borderWidth: 2,
    borderColor: variables.colorBorderPrimary,
    marginBottom: 15,
  },
  changePhotoButton: {
    backgroundColor: variables.colorSurfacePrimary,
    color: variables.colorTextPrimary,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderRadius: variables.borderRadiusLg,
    fontSize: 16,
    marginBottom: 8,
  },
  actions: {
    width: '100%',
    maxWidth: 500,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  changePasswordButton: {
    backgroundColor: '#f44336',
    color: '#fff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: variables.borderRadiusLg,
    fontSize: 16,
  },
  profileForm: {
    backgroundColor: variables.colorSurfaceTertiary,
    borderRadius: variables.borderRadiusLg,
    padding: variables.spacingMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    width: '100%',
    marginBottom: 16,
  },
  formInput: {
    backgroundColor: variables.colorSurfaceSecondary,
    color: variables.colorTextSecondary,
    borderWidth: 1,
    borderColor: variables.colorBorderSecondary,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderRadius: 999,
    marginBottom: 8,
  },
  formButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  cancelButton: {
    backgroundColor: '#ccc',
    color: '#555',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: variables.borderRadiusLg,
    fontSize: 14,
  },
  saveButton: {
    backgroundColor: '#6c63ff',
    color: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: variables.borderRadiusLg,
    fontSize: 14,
  },
});

export default EditarPerfilStyles;
