import { StyleSheet } from 'react-native';
import variables from '../../constants/VariablesBase.styles';

export default StyleSheet.create({
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: variables.modalOverlayBg,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: variables.colorSurfacePrimary,
    borderRadius: variables.borderRadiusMd,
    padding: variables.spacingLg,
    minWidth: 320,
    maxWidth: 400,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  invitacionQrTitle: {
    marginVertical: 0,
    fontSize: 24,
    color: variables.colorTextPrimary,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonGroup: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: variables.borderColor,
    borderRadius: variables.borderRadiusMd,
    overflow: 'hidden',
    marginVertical: variables.spacingMd,
  },
  buttonFormMode: {
    flex: 1,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    fontSize: 16,
    backgroundColor: variables.colorSurfacePrimary,
    color: variables.colorTextPrimary,
    textAlign: 'center',
  },
  buttonFormModeActive: {
    backgroundColor: variables.secondaryGreen,
    color: variables.colorWhite,
  },
  formGroup: {
    padding: variables.spacingMd,
    flexDirection: 'column',
    gap: variables.spacingMd,
    borderWidth: 1,
    borderColor: variables.borderColor,
    borderRadius: variables.borderRadiusMd,
    marginBottom: variables.spacingMd,
  },
  formGroupTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  beneficiariosList: {
    flexDirection: 'column',
    gap: 8,
    maxHeight: 200,
  },
  beneficiarioBtn: {
    backgroundColor: variables.colorSurfaceSecondary,
    color: variables.colorTextSecondary,
    width: '100%',
    padding: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.borderColor,
    borderRadius: variables.borderRadiusMd,
    textAlign: 'left',
    marginBottom: 6,
  },
  beneficiarioBtnSelected: {
    borderColor: variables.selectedBorderColor,
    backgroundColor: variables.colorSurfacePrimary,
    fontWeight: 'bold',
    color: variables.colorTextPrimary,
  },
  label: {
    fontWeight: '500',
    color: variables.colorTextSecondary,
    marginBottom: 4,
  },
  input: {
    padding: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.borderColor,
    borderRadius: variables.borderRadiusMd,
    fontSize: 16,
    backgroundColor: variables.colorSurfaceTertiary,
    color: variables.colorTextTertiary,
    marginBottom: 8,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginTop: 16,
  },
});
