import { StyleSheet } from 'react-native';
import variables from '../../css/VariablesBase.styles';

const styles = StyleSheet.create({
  container: {
    width: '90%',
    alignSelf: 'center',
    marginTop: variables.spacingMd,
    padding: variables.spacingMd,
    backgroundColor: variables.colorSurfacePrimary,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
    minHeight: 200,
    gap: 16,
    borderRadius: variables.borderRadiusMd,
  },
  header: {
    flexDirection: 'column',
    gap: 16,
  },
  headerTitle: {
    color: variables.colorTextPrimary,
    marginBottom: variables.spacingMd,
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
  },
  compraInfo: {
    flexDirection: 'column',
    gap: 32,
    backgroundColor: variables.colorSurfaceTertiary,
    padding: variables.spacingMd,
    borderWidth: 1,
    borderColor: variables.colorBorderTertiary,
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  compraInfoHeader: {
    marginBottom: 12,
  },
  compraInfoDetails: {
    flexDirection: 'column',
    gap: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    backgroundColor: variables.colorSurfaceSecondary,
    borderRadius: variables.borderRadiusMd,
    padding: variables.spacingMd,
    marginTop: 12,
  },
  sectionTitle: {
    fontSize: 18,
    color: variables.colorTextPrimary,
    marginTop: 0,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: variables.colorBorderSecondary,
    fontWeight: 'bold',
  },
  compraInfoText: {
    color: variables.colorTextSecondary,
    lineHeight: 24,
    marginBottom: 12,
  },
  compraInfoTextStrong: {
    color: variables.colorTextPrimary,
    marginRight: 8,
    fontWeight: 'bold',
  },
  productosComprados: {
    flexDirection: 'column',
    backgroundColor: variables.colorSurfaceTertiary,
    padding: variables.spacingMd,
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 24,
    gap: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.colorBorderTertiary,
  },
  productosList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: variables.spacingSm,
    marginTop: 8,
  },
  productosListItem: {
    backgroundColor: '#e0f7fa',
    color: variables.colorSuccess,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderRadius: variables.borderRadiusLg,
    fontSize: variables.fontSizeSm,
    marginRight: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  productoNombre: {
    color: variables.colorTextPrimary,
    fontWeight: 'bold',
    marginRight: 4,
  },
  productoCantidad: {
    color: variables.colorTextSecondary,
    marginRight: 4,
  },
  productoPrecio: {
    color: variables.colorSuccess,
    fontWeight: 'bold',
  },
  loadingText: {
    color: variables.colorTextSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: variables.spacingMd,
    fontSize: 16,
  },
  infoCardLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: variables.colorSurfaceSecondary,
    padding: variables.spacingSm,
    borderRadius: variables.borderRadiusMd,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  infoCardLinkText: {
    flexDirection: 'column',
    borderRightWidth: 1,
    borderRightColor: variables.colorBorderSecondary,
    padding: variables.spacingSm,
    width: '80%',
  },
  infoCardLinkLabel: {
    fontSize: 16,
    marginBottom: 4,
    color: variables.colorTextPrimary,
  },
  infoCardLinkValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: variables.colorTextSecondary,
  },
  infoCardLinkIcon: {
    fontSize: 24,
    color: '#adb5bd',
    marginLeft: 8,
  },
  infoCardLinkIconActive: {
    color: '#343a40',
  },
});

export default styles;
