// Adaptación de Navbar.css a React Native StyleSheet
import { StyleSheet } from 'react-native';
import { light, dark } from '../src/css/VariablesBase.styles';

const VARS = light;

const styles = StyleSheet.create({
  sidebar: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 270,
    height: '100%',
    backgroundColor: VARS.colorSurfacePrimary,
    borderRightWidth: 1,
    borderRightColor: VARS.colorBorderPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    zIndex: 2000,
    flexDirection: 'column',
    transition: 'width 0.4s', // Solo para referencia
  },
  sidebarCollapsed: {
    width: 0,
    overflow: 'hidden',
  },
  sidebarHeader: {
    paddingVertical: 20,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: VARS.colorBorderPrimary,
  },
  headerLogo: {
    width: 150,
    height: 46,
    resizeMode: 'contain',
  },
  sidebarToggle: {
    backgroundColor: VARS.colorSurfaceSecondary,
    color: VARS.colorTextPrimary,
    fontSize: 30,
    borderRadius: VARS.borderRadiusMd,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 0,
    padding: 0,
  },
  sidebarContent: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 18,
  },
  searchForm: {
    borderRadius: VARS.borderRadiusMd,
    minHeight: 48,
    marginVertical: 5,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: VARS.colorSurfaceSecondary,
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flex: 1,
    marginLeft: 15,
    fontSize: 16,
    color: VARS.colorTextPrimary,
    padding: 0,
  },
  menuList: {
    flexDirection: 'column',
    gap: 4,
    marginVertical: 0,
    padding: 0,
  },
  menuItem: {
    borderBottomWidth: 1,
    borderBottomColor: VARS.colorBorderPrimary,
  },
  menuLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: VARS.borderRadiusMd,
    paddingVertical: 12,
    paddingHorizontal: 15,
    textDecorationLine: 'none',
    color: VARS.colorTextPrimary,
  },
  menuLinkActive: {
    color: VARS.colorWhite,
    backgroundColor: VARS.colorBrandPrimary,
  },
  menuLabel: {
    fontSize: 16,
    fontWeight: VARS.fontWeightMedium,
  },
  sidebarFooter: {
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: VARS.colorBorderPrimary,
  },
  themeToggle: {
    width: '100%',
    minHeight: 48,
    borderRadius: VARS.borderRadiusMd,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: VARS.colorSurfaceSecondary,
  },
  themeLabel: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  themeText: {
    fontSize: 16,
    marginLeft: 10,
  },
  themeToggleTrack: {
    height: 24,
    width: 48,
    borderRadius: VARS.borderRadiusFull,
    marginLeft: 'auto',
    backgroundColor: '#c3d1ec',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeToggleIndicator: {
    position: 'absolute',
    top: 3,
    left: 3,
    width: 18,
    height: 18,
    borderRadius: VARS.borderRadiusFull,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  titleHome: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'transparent',
  },
  titleHomeSide: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
});

export default styles;
