import { StyleSheet } from 'react-native';
import { light } from '../src/css/VariablesBase.styles';
const Variables = light;

export default StyleSheet.create({
  home: {
    backgroundColor: Variables.colorSurfacePrimary,
    borderRadius: Variables.borderRadiusLg,
    padding: 20,
    marginVertical: 20,
    borderWidth: 1,
    borderColor: Variables.colorBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    marginTop: 0,
    marginBottom: 20,
    textAlign: 'center',
    color: Variables.colorTextPrimary,
    fontSize: 22,
    fontWeight: 'bold',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomWidth: 2,
    borderBottomColor: '#eee',
    gap: 2,
    marginBottom: 15,
    overflow: 'scroll',
    paddingTop: 0,
    paddingBottom: 0,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: Variables.colorSurfacePrimary,
    fontSize: 16,
    color: Variables.colorTextPrimary,
    borderTopWidth: 2,
    borderTopColor: 'transparent',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    textTransform: 'capitalize',
    marginRight: 2,
    borderRadius: 0,
  },
  tabActive: {
    borderTopColor: '#007bff',
    borderBottomColor: '#007bff',
    fontWeight: 'bold',
  },
  forecast: {
    flexDirection: 'row',
    overflow: 'scroll',
    paddingBottom: 15,
    gap: 15,
  },
  forecastItem: {
    flex: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: Variables.borderRadiusMd,
    backgroundColor: '#f8f9fa',
    minWidth: 80,
    textAlign: 'center',
    marginRight: 10,
  },
  forecastTime: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  forecastIcon: {
    fontSize: 32,
    marginVertical: 5,
  },
  forecastTemp: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212529',
    marginVertical: 5,
  },
  forecastPrecip: {
    fontSize: 13,
    color: '#6c757d',
    margin: 0,
  },
});
