// Adaptación de ServiciosDetalle.css a React Native StyleSheet
import { StyleSheet } from 'react-native';
import { light, dark } from '../../css/VariablesBase.styles';

const VARS = light;

const styles = StyleSheet.create({
  servicioHeader: {
    width: '100%',
    height: 250,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: '#1976d2', // fallback si no hay imagen
    paddingBottom: VARS.spacingMd,
    // backgroundImage: require('../img/reservas/bg-2.jpg'), // Usar ImageBackground en el componente
  },
  servicioHeaderH1: {
    color: '#fff',
    fontSize: 29,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  espacioDetalleDescription: {
    marginTop: 16,
    color: '#fff',
    fontWeight: '600',
    textAlign: 'center',
  },
  detalleCostoHora: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 20,
    marginTop: 10,
    textAlign: 'center',
  },
  servicioImg: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
    borderRadius: VARS.borderRadiusLg,
    borderTopLeftRadius: VARS.borderRadiusLg,
    borderTopRightRadius: VARS.borderRadiusLg,
    borderWidth: 5,
    borderColor: '#eee',
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  bookingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f7f9fc',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    color: '#333',
    fontWeight: '500',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  backArrow: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    fontSize: 24,
    color: '#333',
    padding: 0,
    margin: 0,
  },
  backButtonEspacios: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: '#fff',
    fontSize: 16,
    paddingVertical: 5,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    fontWeight: '600',
  },
  stepIndicator: {
    fontSize: 14,
    color: '#777',
  },
  timeInputs: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    position: 'relative',
  },
  timeInputGroup: {
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
  },
  timeInput: {
    width: 70,
    height: 70,
    fontSize: 24,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: VARS.borderRadiusLg,
    backgroundColor: '#f7f9fc',
    color: '#333',
    fontWeight: '500',
    padding: 0,
  },
  inputLabel: {
    fontSize: 12,
    color: '#888',
    marginTop: 8,
    textTransform: 'uppercase',
  },
  timeColon: {
    fontSize: 48,
    color: '#333',
    alignSelf: 'center',
    paddingBottom: 25,
    marginHorizontal: 5,
  },
  ampmToggle: {
    flexDirection: 'column',
    backgroundColor: '#e0e6ec',
    borderRadius: VARS.borderRadiusLg,
    overflow: 'hidden',
    height: 70,
    width: 50,
  },
  ampmButton: {
    flex: 1,
    borderRadius: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    fontSize: 16,
    fontWeight: '500',
    color: '#777',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
  },
  ampmButtonActive: {
    backgroundColor: '#007bff',
    color: '#fff',
  },
  proceedButton: {
    width: '100%',
    padding: 15,
    backgroundColor: '#007bff',
    color: '#fff',
    borderRadius: VARS.borderRadiusMd,
    fontSize: 18,
    fontWeight: '600',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 3,
  },
  proceedButtonDisabled: {
    backgroundColor: '#ccc',
    color: '#fff',
  },
});

export default styles;
