import { StyleSheet } from 'react-native';
import variables from '../../css/VariablesBase.styles';

const styles = StyleSheet.create({
  container: {
    padding: 8,
    paddingTop: 40,
    backgroundColor: '#f8f9fa',
    minHeight: 200,
    flex: 1,
  },
  header: {
    marginBottom: variables.spacingMd,
  },
  headerTitle: {
    color: variables.colorTextPrimary,
    marginBottom: variables.spacingMd,
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
  },
  reservaInfo: {
    flexDirection: 'column',
    gap: 32,
    backgroundColor: '#fff',
    padding: 24,
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
    marginBottom: 24,
  },
  reservaInfoHeader: {
    marginBottom: 12,
  },
  reservaInfoDetails: {
    flexDirection: 'column',
    gap: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    backgroundColor: variables.colorSurfaceSecondary,
    borderRadius: variables.borderRadiusMd,
    padding: variables.spacingMd,
    marginTop: 12,
  },
  sectionTitle: {
    fontSize: 18,
    color: variables.colorTextPrimary,
    marginTop: 0,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: variables.colorBorderSecondary,
    fontWeight: 'bold',
  },
  infoCardLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: variables.colorSurfaceSecondary,
    padding: variables.spacingSm,
    borderRadius: variables.borderRadiusMd,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: variables.colorBorderPrimary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  infoCardLinkText: {
    flexDirection: 'column',
    borderRightWidth: 1,
    borderRightColor: variables.colorBorderSecondary,
    padding: variables.spacingSm,
    width: '80%',
  },
  infoCardLinkLabel: {
    fontSize: 16,
    marginBottom: 4,
    color: variables.colorTextPrimary,
  },
  infoCardLinkValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: variables.colorTextSecondary,
  },
  infoCardLinkIcon: {
    fontSize: 24,
    color: '#adb5bd',
    marginLeft: 8,
  },
  infoCardLinkIconActive: {
    color: '#343a40',
  },
  horasReservadas: {
    flexDirection: 'column',
    backgroundColor: variables.colorSurfaceTertiary,
    padding: variables.spacingMd,
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 2,
    marginBottom: 24,
    gap: variables.spacingSm,
    borderWidth: 1,
    borderColor: variables.colorBorderTertiary,
  },
  horasList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: variables.spacingSm,
    marginTop: 8,
  },
  horasListItem: {
    backgroundColor: '#e0f7fa',
    color: variables.colorSuccess,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    borderRadius: variables.borderRadiusLg,
    fontSize: variables.fontSizeSm,
    marginRight: 8,
    marginBottom: 8,
  },
  loadingText: {
    color: variables.colorTextSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: variables.spacingMd,
    fontSize: 16,
  },
});

export default styles;
