import { StyleSheet, Dimensions } from 'react-native';
import variables from '../../constants/VariablesBase.styles';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  detalleContainer: {
    maxWidth: 450,
    marginHorizontal: 'auto',
    minHeight: '50%',
    padding: 20,
    boxSizing: 'border-box',
    position: 'relative',
    backgroundColor: '#fff',
    borderRadius: variables.borderRadiusMd,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  reservaImgWrapper: {
    position: 'relative',
    width: '50%',
    alignSelf: 'center',
    marginBottom: 15,
    borderRadius: variables.borderRadiusLg,
    overflow: 'hidden',
  },
  reservaImg: {
    width: '100%',
    height: 180,
    borderRadius: variables.borderRadiusLg,
    borderWidth: 1,
    borderColor: variables.colorWhite,
    resizeMode: 'cover',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  reservaDescription: {
    color: variables.colorWhite,
    width: '80%',
    alignSelf: 'center',
    marginBottom: 8,
  },
  reservaInfoSection: {
    paddingTop: 25,
    paddingHorizontal: 25,
    flexDirection: 'column',
    gap: 0,
    marginBottom: 12,
  },
  reservaInfoText: {
    color: variables.colorTextPrimary,
    marginBottom: 8,
  },
  reservaCatalogoSection: {
    padding: variables.spacingLg,
    flexDirection: 'column',
    gap: 0,
  },
  detalleHeader: {
    textAlign: 'center',
    marginBottom: 30,
  },
  detalleImg: {
    width: 200,
    height: 200,
    borderRadius: 100,
    resizeMode: 'cover',
    borderWidth: 5,
    borderColor: '#eee',
    backgroundColor: '#fff',
    padding: 16,
    alignSelf: 'center',
    marginBottom: 12,
  },
  detalleHeaderTitle: {
    fontSize: 28,
    marginBottom: 5,
    color: '#333',
    fontWeight: 'bold',
  },
  detalleDescription: {
    color: '#777',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 8,
  },
  detalleInfoSection: {
    backgroundColor: '#fff',
    borderRadius: variables.borderRadiusMd,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  detalleInfoSectionTitle: {
    fontSize: 22,
    color: '#333',
    marginTop: 0,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 10,
    fontWeight: 'bold',
  },
  productosGrid: {
    flexDirection: 'column',
    gap: 10,
    padding: variables.spacingMd,
  },
  productoCard: {
    borderRadius: variables.borderRadiusMd,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    height: 200,
    marginBottom: 10,
  },
  productoCardContent: {
    flexDirection: 'column',
    alignItems: 'center',
    width: '60%',
    backgroundColor: variables.colorSurfacePrimary,
    opacity: 0.85,
    borderRadius: variables.borderRadiusMd,
    paddingTop: 16,
    paddingBottom: 8,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  productoImg: {
    width: '40%',
    height: '100%',
    borderRadius: variables.borderRadiusMd,
    resizeMode: 'cover',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
  },
  productoName: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 5,
    color: variables.colorTextPrimary,
    flexWrap: 'wrap',
  },
  productoDescription: {
    fontSize: 12,
    color: variables.colorTextSecondary,
    marginBottom: 8,
    fontWeight: '500',
    flexWrap: 'wrap',
  },
  productoPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#28a745',
    marginBottom: 10,
  },
  addToCartButton: {
    backgroundColor: '#28a745',
    color: '#fff',
    borderRadius: 50,
    paddingVertical: 6,
    paddingHorizontal: 12,
    fontSize: 12,
    fontWeight: '500',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 4,
  },
  productoAnadido: {
    fontSize: 12,
    color: '#28a745',
    marginBottom: 10,
    fontWeight: '500',
  },
  serviciosGrid: {
    flexDirection: 'column',
    gap: 10,
    padding: variables.spacingMd,
  },
  servicioCard: {
    borderRadius: variables.borderRadiusMd,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  servicioName: {
    fontWeight: 'bold',
    marginBottom: 5,
    color: variables.colorTextPrimary,
    fontSize: 16,
  },
  servicioDescription: {
    fontSize: 14,
    color: variables.colorTextSecondary,
    marginBottom: 8,
    lineHeight: 20,
  },
  servicioPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#28a745',
  },
  noProducts: {
    textAlign: 'center',
    color: '#777',
    fontStyle: 'italic',
    paddingVertical: 20,
  },
  categoriasProductos: {
    flexDirection: 'row',
    overflow: 'scroll',
    paddingVertical: 10,
    gap: 10,
    marginBottom: 8,
  },
  spanCategoriaProductos: {
    backgroundColor: variables.colorSurfacePrimary,
    color: variables.colorTextPrimary,
    borderRadius: variables.borderRadiusLg,
    borderWidth: 2,
    borderColor: variables.colorBorderPrimary,
    paddingVertical: variables.spacingSm,
    paddingHorizontal: variables.spacingMd,
    marginRight: 8,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  spanCategoriaProductosActive: {
    backgroundColor: '#007bff',
    color: '#fff',
  },
  selectorTipoEmpresa: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
    backgroundColor: '#f0f2f5',
    padding: 5,
    borderRadius: variables.borderRadiusMd,
  },
  tipoEmpresaButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#fff',
    color: '#555',
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: variables.borderRadiusLg,
    fontWeight: '600',
    textAlign: 'center',
    marginRight: 8,
  },
  tipoEmpresaButtonActive: {
    backgroundColor: '#007bff',
    color: '#fff',
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 2,
  },
});
